### ISSUE TITLE
Installation class lacks log function

### ISSUE THREAD

**Issue by BStaf** [emlyn/sonic-pi-tool#13]
Log is called in the run method, but it doesn't exist in the Installation class. Getting this traceback:

`Traceback (most recent call last):
  File "/usr/local/bin/sonic-pi-tool.py", line 427, in <module>
    cli(obj=None)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/sonic-pi-tool.py", line 392, in start_server
    inst.run()
  File "/usr/local/bin/sonic-pi-tool.py", line 300, in run
    self.log("Running: {}".format(' '.join(args)))
AttributeError: Installation instance has no attribute 'log'
`

**Comment by emlyn** [comment]
Sorry, I made a mistake in a recent change. I've just pushed a fix.
