### ISSUE TITLE
fails to start server (Raspbian/Buster)

### ISSUE THREAD

**Issue by jeffehobbs** [emlyn/sonic-pi-tool#5]
Stock install fails to start-server. Error/output pasted below:

```
jeff@phonotropic:~ $ sonic-pi-tool.py start-server
Found installation at: /usr/lib/sonic-pi
Running: ruby /usr/lib/sonic-pi/server/bin/sonic-pi-server.rb
Failed to load the fast_osc c-extension, falling back to pure Ruby version
Overriding fast_osc c-extension FastOsc::decode_single_message, falling back to pure Ruby version
Sonic Pi server booting...
Using protocol: udp
Detecting port numbers...
Send port: 4558
Listen port: 4557
  - OK
Scsynth port: 4556
  - OK
Scsynth send port: 4556
  - OK
OSC cues port: 4559
  - OK
Erlang port: 4560
  - OK
OSC MIDI out port: 4561
  - OK
OSC MIDI in port: 4562
  - OK
Booting server...


Booting Sonic Pi
----------------

Booting on Raspberry Pi
Jackd not running on system. Starting...
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Failed to connect to session bus for device reservation: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

To bypass device reservation via session bus, set JACK_NO_AUDIO_RESERVATION=1 prior to starting jackd.

Audio device hw:0 cannot be acquired...
Cannot initialize driver
JackServer::Open failed with -1
Failed to open server
Traceback (most recent call last):
ruby: No such file or directory -- /usr/app/server/ruby/bin/task-register.rb (LoadError)
Traceback (most recent call last):
ruby: No such file or directory -- /usr/app/server/ruby/bin/task-register.rb (LoadError)
Boot - Starting the SuperCollider server...
Boot - scsynth -u 4556 -m 131072 -a 1024 -D 0 -R 0 -l 1 -i 2 -o 2 -z 128 -c 128 -U /usr/lib/SuperCollider/plugins:/usr/app/server/native/extra-ugens/ -b 4096 -B 127.0.0.1
Traceback (most recent call last):
ruby: No such file or directory -- /usr/app/server/ruby/bin/task-register.rb (LoadError)
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Failed to connect to session bus for device reservation: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

Audio device hw:0 cannot be acquired...
Cannot initialize driver
JackServer::Open failed with -1
Failed to open server
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
terminate called without an active exception
Traceback (most recent call last):
ruby: No such file or directory -- /usr/app/server/ruby/bin/task-clear.rb (LoadError)
Boot - Unable to boot SuperCollider - boot server log did not report server ready
Failed to start server: Boot - Unable to boot SuperCollider - boot server log did not report server ready
/usr/lib/sonic-pi/server/lib/sonicpi/scsynthexternal.rb:228:in `rescue in boot_and_wait'
/usr/lib/sonic-pi/server/lib/sonicpi/scsynthexternal.rb:221:in `boot_and_wait'
/usr/lib/sonic-pi/server/lib/sonicpi/scsynthexternal.rb:381:in `boot_server_raspberry_pi'
/usr/lib/sonic-pi/server/lib/sonicpi/scsynthexternal.rb:149:in `boot'
/usr/lib/sonic-pi/server/lib/sonicpi/scsynthexternal.rb:37:in `initialize'
/usr/lib/sonic-pi/server/lib/sonicpi/server.rb:78:in `new'
/usr/lib/sonic-pi/server/lib/sonicpi/server.rb:78:in `initialize'
/usr/lib/sonic-pi/server/lib/sonicpi/studio.rb:183:in `new'
/usr/lib/sonic-pi/server/lib/sonicpi/studio.rb:183:in `init_scsynth'
/usr/lib/sonic-pi/server/lib/sonicpi/studio.rb:56:in `initialize'
/usr/lib/sonic-pi/server/lib/sonicpi/lang/sound.rb:125:in `new'
/usr/lib/sonic-pi/server/lib/sonicpi/lang/sound.rb:125:in `block (2 levels) in included'
/usr/lib/sonic-pi/server/bin/sonic-pi-server.rb:177:in `new'
/usr/lib/sonic-pi/server/bin/sonic-pi-server.rb:177:in `<main>'
Server is exiting.
Shutting down GUI...
Traceback (most recent call last):
        2: from /usr/lib/sonic-pi/server/bin/sonic-pi-server.rb:142:in `block in <main>'
        1: from /usr/lib/sonic-pi/server/lib/sonicpi/osc/udp_client.rb:30:in `send'
/usr/lib/sonic-pi/server/lib/sonicpi/osc/udp_client.rb:30:in `send': Connection refused - send(2) (Errno::ECONNREFUSED)
```

**Comment by emlyn** [comment]
This looks like Sonic Pi is failing to start Supercollider, are you able to run Sonic Pi normally (without this script)?

**Comment by emlyn** [comment]
Also, is this the Sonic Pi that comes with Raspbian (I think 3.1)?
Because that one is unfortunately broken, so that might be part of the problem. Could you try downloading and installing the latest version (3.2.2) from [here](https://in-thread.sonic-pi.net/t/sonic-pi-3-2-2-deb-file-for-raspbian-released/3606)?
